# Split this String




In [2]:
s = "Hi there Sam!"

In [3]:
sa=s.split(",")
print(sa)


['Hi there Sam!']


# 2. Use .format() to print the following string.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
Sam=(f" The diameter of {planet}" f" is{diameter} kilometers")

In [7]:
print(Sam)

NameError: name 'Sam' is not defined

# 3. In this nest dictionary grab the word "hello"

In [8]:
d = {'k1'=[1,2,3,
           {'tricky'=['oh','man','inception',
                      {'target'=[1,2,3,'hello']}]}]}

SyntaxError: invalid syntax (2117142211.py, line 1)

# Numpy

In [9]:
import numpy as np


# 4.1 Create an array of 10 seros?

# 4.2 Create an array of 10 fives?

In [10]:
var=np.zeros(10)
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
var1=np.array([5,5,5,5,5,5,5,5,5,5])
var1


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# 5. Create an array of all the even integers from 25 to 35

In [12]:
var3=np.arange(20,35,2)
var3

array([20, 22, 24, 26, 28, 30, 32, 34])

# 6. Create a 3*3 matrix with values ranging from 0 to 8

In [13]:
var4=np.arange(9).reshape(3,3)
var4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 7. Concatenate a and b

# a= np.array([1,2,3]), b=np.array([4,5,6])

In [14]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [15]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [17]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

In [19]:
import pandas as pd

In [22]:
df=pd.dataframe(np.array([[1,2],[3,4],[5,6]])
df

SyntaxError: invalid syntax (1441242616.py, line 2)