# Split this String




In [2]:
s = "Hi there Sam!"

In [3]:
sa=s.split(",")
print(sa)


['Hi there Sam!']


# 2. Use .format() to print the following string.

In [1]:
planet = "Earth"
diameter = 12742

In [2]:
Sam=(f" The diameter of {planet}" f" is{diameter} kilometers")

In [3]:
print(Sam)

 The diameter of Earth is12742 kilometers


# 3. In this nest dictionary grab the word "hello"

In [10]:
d={'k1':[1,2,3,
           {'tricky':['oh','man','inception',
                      {'target':[1,2,3,'hello']}]}]}

In [11]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [9]:
import numpy as np


# 4.1 Create an array of 10 seros?

# 4.2 Create an array of 10 fives?

In [10]:
var=np.zeros(10)
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
var1=np.array([5,5,5,5,5,5,5,5,5,5])
var1


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# 5. Create an array of all the even integers from 25 to 35

In [12]:
var3=np.arange(20,35,2)
var3

array([20, 22, 24, 26, 28, 30, 32, 34])

# 6. Create a 3*3 matrix with values ranging from 0 to 8

In [13]:
var4=np.arange(9).reshape(3,3)
var4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 7. Concatenate a and b

# a= np.array([1,2,3]), b=np.array([4,5,6])

In [14]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [15]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [17]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

In [18]:
import pandas as pd
import numpy as np

In [19]:
df=pd.DataFrame(np.array([[1,2],[3,4],[5,6]]))
df

0  1
0  1  2
1  3  4
2  5  6

# Generate the series of dates from 1st Jan,2023 to 10th Feb,2023

In [20]:
import datetime

In [22]:
df=pd.date_range("01-01-2023","10-02-2023")
df

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

# Create 2D list to DataFrame

In [23]:
lists = [[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]

In [25]:
df=pd.DataFrame(np.array([[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]))
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24